import { AgentContext, AgentDefinition } from '@agent-platform/core';
import { listFilesTool, readFileTool } from '../tools/file-tools';

interface FileInsight {
  path: string;
  type: string;
  exportedSymbols: string[];
  classes: string[];
  functions: string[];
  headings: string[];
}

function detectFileType(filePath: string): string {
  const lower = filePath.toLowerCase();
  if (lower.endsWith('.md')) return 'markdown';
  if (lower.endsWith('.json')) return 'json';
  if (lower.endsWith('.py')) return 'python';
  if (lower.endsWith('.ts') || lower.endsWith('.tsx')) return 'typescript';
  if (lower.endsWith('.js') || lower.endsWith('.jsx')) return 'javascript';
  return 'text';
}

function collectMatches(content: string, regex: RegExp): string[] {
  return [...content.matchAll(regex)]
    .map(match => match[1])
    .filter(Boolean)
    .slice(0, 8);
}

function analyzeFile(path: string, content: string): FileInsight {
  return {
    path,
    type: detectFileType(path),
    exportedSymbols: collectMatches(content, /export\s+(?:const|function|class|type|interface)\s+([A-Za-z0-9_]+)/g),
    classes: collectMatches(content, /class\s+([A-Za-z0-9_]+)/g),
    functions: collectMatches(content, /(?:function\s+([A-Za-z0-9_]+)|const\s+([A-Za-z0-9_]+)\s*=\s*\(|def\s+([A-Za-z0-9_]+)\s*\()/g)
      .map(value => value || '')
      .filter(Boolean)
      .slice(0, 8),
    headings: collectMatches(content, /^#+\s+(.+)$/gm),
  };
}

function buildDocumentation(insights: FileInsight[], input: string): string {
  if (insights.length === 0) {
    return `# Documentation Outline\n\n## Goal\n\n${input}\n\n## Recommended Sections\n\n- Overview\n- Key workflows\n- Configuration\n- Examples\n- Troubleshooting\n\n---\n*Outline generated by Agent Platform Documentation Agent*\n`;
  }

  let output = `# Documentation Summary\n\n`;
  output += `## Overview\n\n`;
  output += `Reviewed ${insights.length} file(s) to generate a concise documentation baseline.\n\n`;

  output += `## Notable Files\n\n`;
  for (const insight of insights) {
    output += `### ${insight.path}\n\n`;
    output += `- **Type**: ${insight.type}\n`;
    if (insight.exportedSymbols.length > 0) {
      output += `- **Exports**: ${insight.exportedSymbols.join(', ')}\n`;
    }
    if (insight.classes.length > 0) {
      output += `- **Classes**: ${insight.classes.join(', ')}\n`;
    }
    if (insight.functions.length > 0) {
      output += `- **Functions**: ${insight.functions.join(', ')}\n`;
    }
    if (insight.headings.length > 0) {
      output += `- **Headings**: ${insight.headings.join(', ')}\n`;
    }
    output += `\n`;
  }

  output += `## Suggested README Structure\n\n`;
  output += `- What this module or project does\n`;
  output += `- Primary entry points and exported APIs\n`;
  output += `- Setup or configuration prerequisites\n`;
  output += `- Usage examples for the most important workflows\n`;
  output += `- Operational caveats and troubleshooting notes\n\n`;

  output += `## Documentation Gaps To Fill\n\n`;
  const filesWithoutExports = insights.filter(item =>
    item.exportedSymbols.length === 0 &&
    item.classes.length === 0 &&
    item.functions.length === 0 &&
    item.headings.length === 0
  );

  if (filesWithoutExports.length > 0) {
    output += `- Add module-level descriptions for ${filesWithoutExports.map(item => item.path).join(', ')}.\n`;
  } else {
    output += `- Public API surface is identifiable; next improvement is richer examples and operational notes.\n`;
  }

  output += `- Document how the main components connect, not just what each file contains.\n\n`;
  output += `---\n*Documentation generated by Agent Platform Documentation Agent*\n`;

  return output;
}

const documentationAgent: AgentDefinition = {
  name: 'documentation-agent',
  version: '1.0.0',
  description: 'Reads files or directories and turns them into a documentation baseline',
  author: 'Agent Platform',
  tags: ['documentation', 'readme', 'api-docs', 'developer-experience'],
  systemPrompt: `You are a documentation engineer. Extract the real structure from code, organize it clearly, and produce documentation that helps another developer get productive fast.`,
  tools: ['read-file', 'list-files'],
  config: {
    model: 'claude-sonnet-4',
    provider: 'anthropic',
    temperature: 0.2,
    maxTokens: 3500,
  },
  async onInit(context: AgentContext) {
    if (!context.tools.has('read-file')) {
      context.tools.set('read-file', readFileTool);
    }
    if (!context.tools.has('list-files')) {
      context.tools.set('list-files', listFilesTool);
    }
  },
  async execute(input: string, context: AgentContext): Promise<string> {
    const target = input.trim();
    const readTool = context.tools.get('read-file');
    const listTool = context.tools.get('list-files');

    const insights: FileInsight[] = [];

    if (readTool) {
      try {
        const file = await readTool.execute({ filePath: target }, context);
        insights.push(analyzeFile(target, file.content));
      } catch {
        // try directory next
      }
    }

    if (insights.length === 0 && listTool && readTool) {
      try {
        const files = await listTool.execute(
          {
            dirPath: target,
            recursive: true,
            pattern: '\\.(ts|tsx|js|jsx|py|md|json)$',
          },
          context
        );

        for (const filePath of files.files.slice(0, 6)) {
          try {
            const file = await readTool.execute({ filePath }, context);
            insights.push(analyzeFile(filePath, file.content));
          } catch {
            continue;
          }
        }
      } catch {
        // fallback to plain text outline
      }
    }

    return buildDocumentation(insights, target);
  },
};

export default documentationAgent;
